use_small_heuristics = "Max"
format_code_in_doc_comments = true
condense_wildcard_suffixes = true
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
wrap_comments = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
